security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Domain\Users\User:
            algorithm: sodium
            time_cost: 3
            memory_cost: 65536

    providers:
        app_user_provider:
            id: App\Infrastructure\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            stateless: true

    access_control:
        - { path: ^/api/v1/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/auth/token/refresh, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/auth/logout, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
            App\Domain\Users\User:
                algorithm: auto
                time_cost: 3
                memory_cost: 10
