# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Domain/Common/AggregateRoot.php'
            - '../src/Domain/**/Tests/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Explicitly register AuthController
    App\Controller\Api\V1\Auth\AuthController:
        autowire: true
        autoconfigure: true
        public: true

    App\Infrastructure\Security\JwtEncoder:
        arguments:
            $privateKeyPath: '%env(resolve:JWT_SECRET_KEY)%'
            $privateKeyPassphrase: '%env(string:JWT_PASSPHRASE)%'
            $issuer: '%env(string:JWT_ISSUER)%'
            $audience: '%env(string:JWT_AUDIENCE)%'

    App\Infrastructure\Security\RefreshTokenHasher:
        arguments:
            $pepper: '%env(string:JWT_PASSPHRASE)%'

    App\Infrastructure\Security\JwtTokenManager:
        arguments:
            $accessTokenTtl: '%env(int:JWT_TOKEN_TTL)%'
            $refreshTokenTtl: '%env(int:JWT_REFRESH_TTL)%'

    App\Domain\Users\UsersRepository: '@App\Infrastructure\Persistence\Doctrine\Repository\DoctrineUsersRepository'
    App\Domain\Auth\TokenManagerInterface: '@App\Infrastructure\Security\JwtTokenManager'

    # User Repository Implementation
    App\Infrastructure\Persistence\Doctrine\Repository\DoctrineUsersRepository:
        autowire: true
        autoconfigure: true

    # User Use Cases
    App\Application\UseCase\User\CreateSchoolAdminUseCase:
        arguments:
            $usersRepository: '@App\Domain\Users\UsersRepository'
            $passwordHasher: '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'

    App\Application\UseCase\User\CreateGuardianUseCase:
        arguments:
            $usersRepository: '@App\Domain\Users\UsersRepository'
            $passwordHasher: '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'

    App\Application\UseCase\User\GetUserByIdUseCase:
        arguments:
            $usersRepository: '@App\Domain\Users\UsersRepository'

    App\Application\UseCase\User\UpdateUserUseCase:
        arguments:
            $usersRepository: '@App\Domain\Users\UsersRepository'

    App\Application\UseCase\User\ListUsersBySchoolUseCase:
        arguments:
            $usersRepository: '@App\Domain\Users\UsersRepository'

    App\Application\UseCase\User\ActivateUserUseCase:
        arguments:
            $usersRepository: '@App\Domain\Users\UsersRepository'

    # User Controller
    App\Controller\Api\V1\UserController:
        autowire: true
        autoconfigure: true
        public: true
        tags: ['controller.service_arguments']

    # Event Subscribers
    App\EventSubscriber\ExceptionSubscriber:
        arguments:
            $environment: '%kernel.environment%'
        tags:
            - { name: kernel.event_subscriber }
